export default {
  payload: [
    {
      id: 0,
      name: 'Ribbok shoes',
      description: 'The best shoes ever!',
      count: 2,
      img: '',
    },
    {
      id: 1,
      name: 'Some staff',
      description: 'Look at this variant. It is the better solution for you and your life',
      count: 1,
      img: '',
    },
    {
      id: 2,
      name: 'Abbibbas',
      description: 'For real gopota!',
      count: 3,
      img: '',
    },
    {
      id: 3,
      name: 'Ribbok suit',
      description: 'Whant to be the best gopnik ever? Than but this one!',
      count: 10,
      img: '',
    },
    {
      id: 4,
      name: 'Shoes',
      description: 'The best shoes ever!',
      count: 4,
      img: '',
    },
    {
      id: 5,
      name: 'Another one',
      description: '',
      count: 1,
      img: '',
    },
    {
      id: 6,
      name: 'And new one',
      description: 'best!',
      count: 1,
      img: '',
    },
    {
      id: 7,
      name: 'Jump Park',
      description: '',
      count: 3,
      img: '',
    },
    {
      id: 8,
      name: 'Killers association',
      description: '',
      count: 1,
      img: '',
    },
    {
      id: 9,
      name: 'Otto Dix',
      description: '',
      count: 3,
      img: '',
    },
    {
      id: 10,
      name: 'Zippo',
      description: '',
      count: 5,
      img: '',
    },
    {
      id: 11,
      name: 'Intura',
      description: '',
      count: 15,
      img: '',
    },
    {
      id: 12,
      name: 'TNT service',
      description: 'Postman',
      count: 1,
      img: '',
    },
    {
      id: 13,
      name: 'Intrumant obirutial',
      description: '',
      count: 1,
      img: '',
    },
    {
      id: 14,
      name: 'Application',
      description: '',
      count: 7,
      img: '',
    },
    {
      id: 15,
      name: 'Ultra momo',
      description: 'Do you want momo?!',
      count: 3,
      img: '',
    },
    {
      id: 16,
      name: 'Opium',
      description: 'Drugs!',
      count: 11,
      img: '',
    },
    {
      id: 17,
      name: 'Abdula',
      description: 'The best ever!',
      count: 1,
      img: '',
    },
    {
      id: 18,
      name: 'Titos',
      description: '',
      count: 3,
      img: '',
    },
  ],
};
